services:

  rabbit-ms:
    image: rabbitmq:4-management
    hostname: rabbitmq
    environment:
      RABBITMQ_ERLANG_COOKIE: "secret123"
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 30s
    extends:
      file: common-config.yml
      service: network-deploy-service







  configserver:
    image: "ipsitasarkar/configserver:v3"
    container_name: configserver-ms
    ports:
      - "8071:8071"
    depends_on:
      rabbit-ms:
        condition: service_healthy
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_CLOUD_CONFIG_SERVER_GIT_URI: https://github.com/ipsitasarkar-dev/EazyBank-config.git
    healthcheck:
      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 30s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-base-config




  accounts:
    image: "ipsitasarkar/accounts:v3"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    depends_on:
      configserver:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "accounts"
    extends:
      file: common-config.yml
      service: microservice-configserver-config


  cards:
    image: "ipsitasarkar/cards:v3"
    container_name: cards-ms
    ports:
      - "9000:8080"
    depends_on:
      configserver:
        condition: service_healthy
    extends:
      file: common-config.yml
      service: microservice-configserver-config

  loans:
    image: "ipsitasarkar/loans:v3"
    container_name: loans-ms
    ports:
      - "8090:8090"
    depends_on:
      configserver:
        condition: service_healthy
    extends:
      file: common-config.yml
      service: microservice-configserver-config


networks:
  yourbank:
    driver: "bridge"

